apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  rhtap/gitops: qcoctasdw-python 
  janus-idp.io/tekton: qcoctasdw-python
  backstage.io/kubernetes-id: qcoctasdw-python
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: qcoctasdw-python
resources: 
- application-dev.yaml 
- application-stage.yaml 
- application-prod.yaml  